name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: makeTests
      run: make tests_run
