name: Tests

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:

  hello-world:
    runs-on: ubuntu-20.04
    steps:
    - name: Say hello world
      run: echo "Welcome to the Github Actions workshop !"

  unit-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v2

    - name: Run make
      run: make

    - name: Make tests run
      continue-on-error: true
      run: make tests_run > coverage_outputs

    - name: Compute coverage
      continue-on-error: true
      run: make coverage >> coverage_outputs

    - name: Upload coverage output
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: coverage_outputs
        path: coverage_outputs

  functional-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Functional test
        run: make && ./functional-test.sh > function-tests_outputs

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: function-tests_outputs
          path: function-tests_outputs