name: Tests

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ master ]

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
    - name: Say hello world
      run: echo "Welcome to the Github Actions workshop !"
  unit-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: makeTests
      run: make tests_run
    - name: coverage
      run: make coverage
    - name: fclean
      run: make fclean
